name: smart_school_assistant
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Required for Flutter's built-in text
    sdk: flutter

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # PDF & Printing
  pdf: ^3.10.8
  printing: ^5.12.0
  image_picker: ^1.1.2

  # Excel Export/Import
  excel: ^4.0.3
  file_picker: ^8.0.0+1
  share_plus: ^10.0.0

  # Charts and Analytics
  fl_chart: ^0.66.1

  # URL and Email
  url_launcher: ^6.2.6

  # Utilities
  intl: ^0.20.2
  collection: ^1.18.0
  shared_preferences: ^2.2.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true