// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGFXM_lLoWntYZbK9_xo9gD_-59MOFOrc',
    appId: '1:893583360512:web:62aa8a98ab25f5c2d98ee5',
    messagingSenderId: '893583360512',
    projectId: 'smart-school-assistant-b9340',
    authDomain: 'smart-school-assistant-b9340.firebaseapp.com',
    storageBucket: 'smart-school-assistant-b9340.firebasestorage.app',
    measurementId: 'G-JLKZ0C0ZKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRuNh2zL4Q4jLdnwdAv-qHiccBkPzaJzk',
    appId: '1:893583360512:android:2c331acced876ff7d98ee5',
    messagingSenderId: '893583360512',
    projectId: 'smart-school-assistant-b9340',
    storageBucket: 'smart-school-assistant-b9340.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoFSgjM5Z0IQEYQIQS0By3YlWN3WapAb4',
    appId: '1:893583360512:ios:ebe11f94d41e1e8dd98ee5',
    messagingSenderId: '893583360512',
    projectId: 'smart-school-assistant-b9340',
    storageBucket: 'smart-school-assistant-b9340.firebasestorage.app',
    iosClientId: '893583360512-7uogj9jco26f8q4h7hko97mlvavd3ak8.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartSchoolAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoFSgjM5Z0IQEYQIQS0By3YlWN3WapAb4',
    appId: '1:893583360512:ios:ebe11f94d41e1e8dd98ee5',
    messagingSenderId: '893583360512',
    projectId: 'smart-school-assistant-b9340',
    storageBucket: 'smart-school-assistant-b9340.firebasestorage.app',
    iosClientId: '893583360512-7uogj9jco26f8q4h7hko97mlvavd3ak8.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartSchoolAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGFXM_lLoWntYZbK9_xo9gD_-59MOFOrc',
    appId: '1:893583360512:web:c227a07d9a0beacbd98ee5',
    messagingSenderId: '893583360512',
    projectId: 'smart-school-assistant-b9340',
    authDomain: 'smart-school-assistant-b9340.firebaseapp.com',
    storageBucket: 'smart-school-assistant-b9340.firebasestorage.app',
    measurementId: 'G-8ZJNG7VWL0',
  );
}
