import 'package:hive/hive.dart';

part 'models.g.dart'; // Will be generated by Hive

@HiveType(typeId: 0)
class Student extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String fullName;

  @HiveField(2)
  String? photoPath; // Path to the image file on the device

  @HiveField(3)
  DateTime dateOfBirth;

  @HiveField(4)
  String gender;

  @HiveField(5)
  String classSectionId; // Links to a ClassSection

  Student({required this.id, required this.fullName, this.photoPath, required this.dateOfBirth, required this.gender, required this.classSectionId});
}

@HiveType(typeId: 1)
class Teacher extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String fullName;

  Teacher({required this.id, required this.fullName});
}

@HiveType(typeId: 2)
class Subject extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String name;

  @HiveField(2)
  String teacherId; // Links to a Teacher

  Subject({required this.id, required this.name, required this.teacherId});
}

@HiveType(typeId: 3)
class ClassSection extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String name; // e.g., "Grade 7A"

  ClassSection({required this.id, required this.name});
}

@HiveType(typeId: 4)
class Score extends HiveObject {
  @HiveField(0)
  String studentId;

  @HiveField(1)
  String subjectId;

  @HiveField(2)
  String assessmentType; // e.g., "Homework", "Mid-term", "Final Exam"

  @HiveField(3)
  double marks;

  @HiveField(4)
  DateTime date;

  Score({required this.studentId, required this.subjectId, required this.assessmentType, required this.marks, required this.date});
}

@HiveType(typeId: 5)
class AttendanceRecord extends HiveObject {
  @HiveField(0)
  String studentId;

  @HiveField(1)
  DateTime date;

  @HiveField(2)
  String status; // e.g., "Present", "Absent", "Late"

  AttendanceRecord({required this.studentId, required this.date, required this.status});
}

@HiveType(typeId: 6)
class TimeTableEntry extends HiveObject {
  @HiveField(0)
  String dayOfWeek; // e.g., "Monday"

  @HiveField(1)
  String period; // e.g., "Period 1 (8:00-8:40)"

  @HiveField(2)
  String subjectId;

  @HiveField(3)
  String classSectionId;

  TimeTableEntry({required this.dayOfWeek, required this.period, required this.subjectId, required this.classSectionId});
}