import 'package:hive/hive.dart';

part 'models.g.dart'; // Will be generated by Hive

@HiveType(typeId: 0)
class Student extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String fullName;

  @HiveField(2)
  String? photoPath; // Path to the image file on the device

  @HiveField(3)
  DateTime dateOfBirth;

  @HiveField(4)
  String gender;

  @HiveField(5)
  String classSectionId; // Links to a ClassSection

  @HiveField(6)
  String? phoneNumber;

  @HiveField(7)
  String? address;

  @HiveField(8)
  String? emergencyContactName;

  @HiveField(9)
  String? emergencyContactPhone;

  @HiveField(10)
  String? email;

  @HiveField(11)
  DateTime? enrollmentDate;

  @HiveField(12)
  String? studentId; // School ID number

  @HiveField(13)
  String? grade; // Grade level (e.g., "Grade 7", "Grade 8")

  @HiveField(14)
  String? bloodType;

  @HiveField(15)
  String? medicalConditions;

  @HiveField(16)
  String? nationality;

  @HiveField(17)
  String? religion;

  Student({
    required this.id,
    required this.fullName,
    this.photoPath,
    required this.dateOfBirth,
    required this.gender,
    required this.classSectionId,
    this.phoneNumber,
    this.address,
    this.emergencyContactName,
    this.emergencyContactPhone,
    this.email,
    this.enrollmentDate,
    this.studentId,
    this.grade,
    this.bloodType,
    this.medicalConditions,
    this.nationality,
    this.religion,
  });

  // Helper method to calculate age
  int get age {
    final now = DateTime.now();
    int age = now.year - dateOfBirth.year;
    if (now.month < dateOfBirth.month ||
        (now.month == dateOfBirth.month && now.day < dateOfBirth.day)) {
      age--;
    }
    return age;
  }

  // Helper method to get formatted enrollment date
  String get formattedEnrollmentDate {
    if (enrollmentDate == null) return 'Not set';
    return '${enrollmentDate!.day}/${enrollmentDate!.month}/${enrollmentDate!.year}';
  }
}

@HiveType(typeId: 1)
class Teacher extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String fullName;

  Teacher({required this.id, required this.fullName});
}

@HiveType(typeId: 2)
class Subject extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String name;

  @HiveField(2)
  String teacherId; // Links to a Teacher

  Subject({required this.id, required this.name, required this.teacherId});
}

@HiveType(typeId: 3)
class ClassSection extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String name; // e.g., "Grade 7A"

  ClassSection({required this.id, required this.name});
}

@HiveType(typeId: 4)
class Score extends HiveObject {
  @HiveField(0)
  String studentId;

  @HiveField(1)
  String subjectId;

  @HiveField(2)
  String assessmentType; // e.g., "Homework", "Mid-term", "Final Exam"

  @HiveField(3)
  double marks;

  @HiveField(4)
  DateTime date;

  Score({required this.studentId, required this.subjectId, required this.assessmentType, required this.marks, required this.date});
}

@HiveType(typeId: 5)
class AttendanceRecord extends HiveObject {
  @HiveField(0)
  String studentId;

  @HiveField(1)
  DateTime date;

  @HiveField(2)
  String status; // e.g., "Present", "Absent", "Late"

  AttendanceRecord({required this.studentId, required this.date, required this.status});
}

@HiveType(typeId: 6)
class TimeTableEntry extends HiveObject {
  @HiveField(0)
  String dayOfWeek; // e.g., "Monday"

  @HiveField(1)
  String period; // e.g., "Period 1 (8:00-8:40)"

  @HiveField(2)
  String subjectId;

  @HiveField(3)
  String classSectionId;

  TimeTableEntry({required this.dayOfWeek, required this.period, required this.subjectId, required this.classSectionId});
}
// PASTE THE NEW CODE HERE
@HiveType(typeId: 7)
class Period extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String name; // e.g., "Period 1", "Break"

  @HiveField(2)
  String time; // e.g., "8:00 - 8:40"

  @HiveField(3)
  bool isBreak;

  Period({required this.id, required this.name, required this.time, this.isBreak = false});
}

@HiveType(typeId: 8)
class InventoryItem extends HiveObject {
 @HiveField(0)
 String id;

 @HiveField(1)
 String name; // e.g., "Book", "Table", "Computer"

 @HiveField(2)
 int quantity;

 @HiveField(3)
 String type; // e.g., "Educational", "Furniture", "Electronics"

 @HiveField(4)
 String condition; // "Worked" or "Not Worked"

 @HiveField(5)
 String description;

 @HiveField(6)
 DateTime dateAdded;

 InventoryItem({
   required this.id,
   required this.name,
   required this.quantity,
   required this.type,
   required this.condition,
   required this.description,
   required this.dateAdded,
 });
}

@HiveType(typeId: 9)
class DataRecord extends HiveObject {
 @HiveField(0)
 String id;

 @HiveField(1)
 String title;

 @HiveField(2)
 String category; // e.g., "Policies", "Student Records", "Teacher Records", "Administrative"

 @HiveField(3)
 String content;

 @HiveField(4)
 String? attachmentPath; // Path to attached file/document

 @HiveField(5)
 String priority; // "Low", "Medium", "High", "Critical"

 @HiveField(6)
 String status; // "Active", "Archived", "Draft"

 @HiveField(7)
 DateTime dateCreated;

 @HiveField(8)
 DateTime? lastModified;

 @HiveField(9)
 String createdBy; // User who created the record

 DataRecord({
   required this.id,
   required this.title,
   required this.category,
   required this.content,
   this.attachmentPath,
   required this.priority,
   required this.status,
   required this.dateCreated,
   this.lastModified,
   required this.createdBy,
 });
}

@HiveType(typeId: 10)
class Assessment extends HiveObject {
 @HiveField(0)
 String id;

 @HiveField(1)
 String name; // e.g., "Quiz", "Mid-term", "Final Exam", "Project"

 @HiveField(2)
 String subjectId; // Links to Subject

 @HiveField(3)
 String classSectionId; // Links to ClassSection

 @HiveField(4)
 String semesterId; // Links to Semester

 @HiveField(5)
 double weight; // Weight in percentage (e.g., 0.2 for 20%)

 @HiveField(6)
 double maxMarks; // Maximum marks for this assessment

 @HiveField(7)
 DateTime dueDate;

 @HiveField(8)
 String description;

 Assessment({
   required this.id,
   required this.name,
   required this.subjectId,
   required this.classSectionId,
   required this.semesterId,
   required this.weight,
   required this.maxMarks,
   required this.dueDate,
   required this.description,
 });
}

@HiveType(typeId: 11)
class Semester extends HiveObject {
 @HiveField(0)
 String id;

 @HiveField(1)
 String name; // e.g., "Semester 1", "Semester 2"

 @HiveField(2)
 String academicYear; // e.g., "2023-2024"

 @HiveField(3)
 DateTime startDate;

 @HiveField(4)
 DateTime endDate;

 @HiveField(5)
 bool isActive; // Whether this semester is currently active

 Semester({
   required this.id,
   required this.name,
   required this.academicYear,
   required this.startDate,
   required this.endDate,
   required this.isActive,
 });
}

@HiveType(typeId: 12)
class AssessmentScore extends HiveObject {
 @HiveField(0)
 String id;

 @HiveField(1)
 String studentId; // Links to Student

 @HiveField(2)
 String assessmentId; // Links to Assessment

 @HiveField(3)
 double marksObtained; // Marks obtained by student

 @HiveField(4)
 DateTime dateRecorded;

 @HiveField(5)
 String recordedBy; // Teacher who recorded the score

 AssessmentScore({
   required this.id,
   required this.studentId,
   required this.assessmentId,
   required this.marksObtained,
   required this.dateRecorded,
   required this.recordedBy,
 });
}